package com.rohan.Khoj.config;

 // Import all DTOs (e.g., PatientDTO, DoctorDTO, ClinicDTO, AppointmentDTO, Request/Update DTOs, Affiliation DTOs)
// Explicit imports for inner classes (MobileNumberWrapperDTO) for clarity in converters
import com.rohan.Khoj.common.MobileNumberWrapperDTO;

import com.rohan.Khoj.auth.ClinicRegistrationRequestDTO;
import com.rohan.Khoj.auth.DoctorRegistrationRequestDTO;
import com.rohan.Khoj.auth.PatientRegistrationRequestDTO;
 // Import all Entities (e.g., PatientEntity, DoctorEntity, ClinicEntity, AppointmentDetailEntity, DoctorClinicAffiliationEntity)
import org.modelmapper.ModelMapper;
import org.modelmapper.PropertyMap;
import org.modelmapper.Converter; // Import Converter
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import com.rohan.Khoj.patient.PatientUpdateRequestDTO;
import com.rohan.Khoj.appointment.AppointmentDetailEntity;
import com.rohan.Khoj.doctor.DoctorDTO;
import com.rohan.Khoj.clinic.ClinicUpdateRequestDTO;
import com.rohan.Khoj.appointment.AppointmentDTO;
import com.rohan.Khoj.appointment.AppointmentUpdateRequestDTO;
import com.rohan.Khoj.patient.PatientEntity;
import com.rohan.Khoj.clinic.ClinicEntity;
import com.rohan.Khoj.doctor.DoctorUpdateRequestDTO;
import com.rohan.Khoj.doctor.DoctorEntity;
import com.rohan.Khoj.clinic.ClinicDTO;
import com.rohan.Khoj.appointment.AppointmentRequestDTO;
import com.rohan.Khoj.affiliation.DoctorClinicAffiliationEntity;
import com.rohan.Khoj.patient.PatientDTO;

@Configuration
public class ModelMapperConfig {

    @Bean
    public ModelMapper modelMapper(PasswordEncoder passwordEncoder) {
        ModelMapper modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setAmbiguityIgnored(true); // Allows multiple sources to map to same target (with skips)

        // Set the matching strategy to STRICT to prevent ambiguous automatic mappings.
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);

        // --- Common Converters ---

        // Converter: Set<String> to List<String> (for phone numbers in response DTOs, to ensure consistent order)
        Converter<Set<String>, List<String>> setToListSortedConverter = context -> {
            if (context.getSource() == null) {
                return null;
            }
            return context.getSource().stream()
                    .sorted() // Natural alphabetical/numerical order for strings
                    .collect(Collectors.toList());
        };

        // --- Mappings for Patient Entities and DTOs ---

        // PatientRegistrationRequestDTO -> PatientEntity
        modelMapper.addMappings(new PropertyMap<PatientRegistrationRequestDTO, PatientEntity>() {
            @Override
            protected void configure() {
                map().setEmailId(source.getEmailId()); // DTO 'email' to Entity 'emailId'
                skip().setPassword(null);      // Handled in service
                skip().setId(null);                  // Generated by DB
                skip().setCreatedAt(null);           // Set by @PrePersist or service
                skip().setUpdatedAt(null);           // Set by @PreUpdate or service

            }
        });

        // PatientUpdateRequestDTO -> PatientEntity (for updating existing entity)
        modelMapper.addMappings(new PropertyMap<PatientUpdateRequestDTO, PatientEntity>() {
            @Override
            protected void configure() {
                skip().setUsername(null);           // Handled in service (uniqueness check with exclusion)
                skip().setEmailId(null);            // Handled in service (uniqueness check with exclusion)
                skip().setPassword(null);     // Handled in service (password hashing)
                skip().setId(null);
                skip().setCreatedAt(null);
                skip().setUpdatedAt(null);

            }
        });

        // PatientEntity -> PatientDTO (for response/retrieval)
        modelMapper.addMappings(new PropertyMap<PatientEntity, PatientDTO>() {
            @Override
            protected void configure() {
                map().setEmailId(source.getEmailId()); // Ensure consistent mapping if field name varies
            }
        });

        // --- Mappings for Doctor Entities and DTOs ---

        // DoctorRegistrationRequestDTO -> DoctorEntity
        modelMapper.addMappings(new PropertyMap<DoctorRegistrationRequestDTO, DoctorEntity>() {
            @Override
            protected void configure() {
                map().setEmailId(source.getEmailId());
                skip().setPassword(null);
                skip().setId(null);
                skip().setCreatedAt(null);
                skip().setUpdatedAt(null);
                skip().setClinicAffiliations(null); // Relationships set separately

            }
        });

        // DoctorUpdateRequestDTO -> DoctorEntity
        modelMapper.addMappings(new PropertyMap<DoctorUpdateRequestDTO, DoctorEntity>() {
            @Override
            protected void configure() {
                skip().setUsername(null);
                skip().setEmailId(null);
                skip().setPassword(null);
                skip().setRegistrationNumber(null); // Handled in service
                skip().setId(null);
                skip().setCreatedAt(null);
                skip().setUpdatedAt(null);
                skip().setClinicAffiliations(null);

            }
        });

        // DoctorEntity -> DoctorDTO
        modelMapper.addMappings(new PropertyMap<DoctorEntity, DoctorDTO>() {
            @Override
            protected void configure() {
            }
        });

        // --- Mappings for Clinic Entities and DTOs ---

        // ClinicRegistrationRequestDTO -> ClinicEntity
        modelMapper.addMappings(new PropertyMap<ClinicRegistrationRequestDTO, ClinicEntity>() {
            @Override
            protected void configure() {
                map().setName(source.getName()); // DTO 'name' to Entity 'name'
                map().setEmailId(source.getEmailId());
                skip().setPassword(null);
                skip().setId(null);
                skip().setCreatedAt(null);
                skip().setUpdatedAt(null);
                skip().setDoctorAffiliations(null);

            }
        });

        // ClinicUpdateRequestDTO -> ClinicEntity
        modelMapper.addMappings(new PropertyMap<ClinicUpdateRequestDTO, ClinicEntity>() {
            @Override
            protected void configure() {
                skip().setUsername(null);
                skip().setEmailId(null);
                skip().setPassword(null);
                skip().setName(null); // Handled in service
                skip().setId(null);
                skip().setCreatedAt(null);
                skip().setUpdatedAt(null);
                skip().setDoctorAffiliations(null);

            }
        });

        // ClinicEntity -> ClinicDTO
        modelMapper.addMappings(new PropertyMap<ClinicEntity, ClinicDTO>() {
            @Override
            protected void configure() {
            }
        });

        // --- Mappings for Appointment Entities and DTOs ---

        // AppointmentRequestDTO -> AppointmentDetailEntity
        modelMapper.addMappings(new PropertyMap<AppointmentRequestDTO, AppointmentDetailEntity>() {
            @Override
            protected void configure() {
                skip().setId(null);      // Generated by DB
                skip().setStatus(null);  // Set by service
                skip().setReason(null);
                // skip().setCreatedAt(null); // Timestamps
                // skip().setUpdatedAt(null);
            }
        });

        // AppointmentUpdateRequestDTO -> AppointmentDetailEntity
        modelMapper.addMappings(new PropertyMap<AppointmentUpdateRequestDTO, AppointmentDetailEntity>() {
            @Override
            protected void configure() {
                skip().setId(null);
                skip().setReason(null);
                // skip().setCreatedAt(null);
                // skip().setUpdatedAt(null);
            }
        });

        // Define the single, authoritative mapping for AppointmentDetailEntity -> AppointmentDTO.
        modelMapper.typeMap(AppointmentDetailEntity.class, AppointmentDTO.class).addMappings(mapper -> {
            mapper.map(src -> src.getPatient().getId(), AppointmentDTO::setPatientId);
            mapper.map(src -> src.getPatient().getFirstName() + " " + src.getPatient().getLastName(), AppointmentDTO::setPatientFullName);
        });

        return modelMapper;
    }
}